# Generated by Django 2.2.16 on 2021-02-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=80)),
                ('done', models.BooleanField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
